In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df["Churn"].value_counts()
#data imbalance var 
df.duplicated().value_counts()
df["customerID"].duplicated().value_counts()
#duplicate customer veya veri yok 


#genel plan 
#veriler genelde object onları encode edicem 
#verileri column column ele alıcam  hepsine detaylı bakmaya çalışıcam
#prepocesingeden sonr alogistic regresoyn 
#en son metriclerle değerlendirme 



df["gender"].unique()


df_clean = df.copy()
df_clean = df_clean.drop(columns=["customerID"])

In [5]:
df_clean = pd.get_dummies(df_clean, columns=["gender"], drop_first=True)

In [6]:
df_clean["gender_Male"]

0       False
1        True
2        True
3        True
4       False
        ...
7038     True
7039    False
7040    False
7041     True
7042     True
Name: gender_Male, Length: 7043, dtype: bool

In [7]:
df_clean

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Male
0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,False
1,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No,True
2,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,True
3,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,True
4,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,True
7039,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,False
7040,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,False
7041,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,True
7042,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,True

In [8]:
df_clean["gender_Male"]= df_clean["gender_Male"].astype(int)

In [9]:
df_clean["Partner"] = df_clean["Partner"].str.strip().map({"Yes": 1, "No": 0})

In [10]:
import numpy as np

obj_cols = df_clean.select_dtypes(include=["object"]).columns

for c in obj_cols:
    vals = set(df_clean[c].dropna().astype(str).str.strip().unique())
    if vals.issubset({"Yes", "No"}):
        df_clean[c] = df_clean[c].astype(str).str.strip().map({"Yes": 1, "No": 0})

In [11]:
obj_cols = df_clean.select_dtypes(include=["object"]).columns
obj_cols

Index(['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaymentMethod', 'TotalCharges'],
      dtype='object')

In [12]:
df_clean["OnlineSecurity"].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [13]:
df_clean["OnlineSecurity"] = (
    df_clean["OnlineSecurity"].astype(str).str.replace("No internet service", "No")
)

In [14]:
df_clean["OnlineSecurity"].unique()

array(['No', 'Yes'], dtype=object)

In [15]:
df_clean["OnlineSecurity"] = df_clean["OnlineSecurity"].astype(str).str.strip().map({"Yes": 1, "No": 0})

In [16]:
df_clean["OnlineSecurity"].unique()

array([0, 1])

In [17]:
df_clean

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Male
0,0,1,0,1,0,No phone service,DSL,0,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0,0
1,0,0,0,34,1,No,DSL,1,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0,1
2,0,0,0,2,1,No,DSL,1,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1,1
3,0,0,0,45,0,No phone service,DSL,1,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,1
4,0,0,0,2,1,No,Fiber optic,0,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,1,1,24,1,Yes,DSL,1,No,Yes,Yes,Yes,Yes,One year,1,Mailed check,84.80,1990.5,0,1
7039,0,1,1,72,1,Yes,Fiber optic,0,Yes,Yes,No,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.9,0,0
7040,0,1,1,11,0,No phone service,DSL,1,No,No,No,No,No,Month-to-month,1,Electronic check,29.60,346.45,0,0
7041,1,1,0,4,1,Yes,Fiber optic,0,No,No,No,No,No,Month-to-month,1,Mailed check,74.40,306.6,1,1
7042,0,0,0,66,1,No,Fiber optic,1,No,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0,1

In [18]:
for col in obj_cols  :
    print(f"\n🧩 {col} unique values:")
    print(df_clean[col].unique())

🧩 MultipleLines unique values:
['No phone service' 'No' 'Yes']

🧩 InternetService unique values:
['DSL' 'Fiber optic' 'No']

🧩 OnlineSecurity unique values:
[0 1]

🧩 OnlineBackup unique values:
['Yes' 'No' 'No internet service']

🧩 DeviceProtection unique values:
['No' 'Yes' 'No internet service']

🧩 TechSupport unique values:
['No' 'Yes' 'No internet service']

🧩 StreamingTV unique values:
['No' 'Yes' 'No internet service']

🧩 StreamingMovies unique values:
['No' 'Yes' 'No internet service']

🧩 Contract unique values:
['Month-to-month' 'One year' 'Two year']

🧩 PaymentMethod unique values:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

🧩 TotalCharges unique values:
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']

In [19]:
 df_clean["TotalCharges"].str.strip()
df_clean["TotalCharges"].isnull().sum()

np.int64(0)

In [20]:
 df_clean["TotalCharges"]= pd.to_numeric( df_clean["TotalCharges"],errors="coerce")

In [21]:
type(df_clean["TotalCharges"][0])

numpy.float64

In [22]:
df_clean["TotalCharges"].unique()

array([  29.85, 1889.5 ,  108.15, ...,  346.45,  306.6 , 6844.5 ],
      shape=(6531,))

In [23]:
for col in obj_cols:
    print(f"\n🧩 {col}")
    print(df_clean[col].value_counts())

🧩 MultipleLines
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

🧩 InternetService
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

🧩 OnlineSecurity
OnlineSecurity
0    5024
1    2019
Name: count, dtype: int64

🧩 OnlineBackup
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

🧩 DeviceProtection
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

🧩 TechSupport
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

🧩 StreamingTV
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

🧩 StreamingMovies
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

🧩 Contract
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

🧩 PaymentMethod
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

🧩 TotalCharges
TotalCharges
20.20      11
19.75       9
20.05       8
19.90       8
19.65       8
           ..
6849.40     1
692.35      1
130.15      1
3211.90     1
6844.50     1
Name: count, Length: 6530, dtype: int64

In [24]:
obj_cols=obj_cols.drop("TotalCharges",errors="coence")

In [25]:
obj_cols=obj_cols.drop("OnlineSecurity",errors="coence")

In [26]:
obj_cols

Index(['MultipleLines', 'InternetService', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaymentMethod'],
      dtype='object')

In [27]:
for i in obj_cols:
    print(f"\n🧩 {col} unique values:")
    print(df_clean[i].unique())

🧩 TotalCharges unique values:
['No phone service' 'No' 'Yes']

🧩 TotalCharges unique values:
['DSL' 'Fiber optic' 'No']

🧩 TotalCharges unique values:
['Yes' 'No' 'No internet service']

🧩 TotalCharges unique values:
['No' 'Yes' 'No internet service']

🧩 TotalCharges unique values:
['No' 'Yes' 'No internet service']

🧩 TotalCharges unique values:
['No' 'Yes' 'No internet service']

🧩 TotalCharges unique values:
['No' 'Yes' 'No internet service']

🧩 TotalCharges unique values:
['Month-to-month' 'One year' 'Two year']

🧩 TotalCharges unique values:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [28]:
df_clean.reset_index()

,index,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Male
0,0,0,1,0,1,0,No phone service,DSL,0,Yes,...,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0,0
1,1,0,0,0,34,1,No,DSL,1,No,...,No,No,No,One year,0,Mailed check,56.95,1889.50,0,1
2,2,0,0,0,2,1,No,DSL,1,Yes,...,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1,1
3,3,0,0,0,45,0,No phone service,DSL,1,No,...,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0,1
4,4,0,0,0,2,1,No,Fiber optic,0,No,...,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,7038,0,1,1,24,1,Yes,DSL,1,No,...,Yes,Yes,Yes,One year,1,Mailed check,84.80,1990.50,0,1
7039,7039,0,1,1,72,1,Yes,Fiber optic,0,Yes,...,No,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.90,0,0
7040,7040,0,1,1,11,0,No phone service,DSL,1,No,...,No,No,No,Month-to-month,1,Electronic check,29.60,346.45,0,0
7041,7041,1,1,0,4,1,Yes,Fiber optic,0,No,...,No,No,No,Month-to-month,1,Mailed check,74.40,306.60,1,1
7042,7042,0,0,0,66,1,No,Fiber optic,1,No,...,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.50,0,1

In [29]:
for i in obj_cols:
    print(f"\n🧩 {i} unique values:")
    print(df_clean[i].unique())

🧩 MultipleLines unique values:
['No phone service' 'No' 'Yes']

🧩 InternetService unique values:
['DSL' 'Fiber optic' 'No']

🧩 OnlineBackup unique values:
['Yes' 'No' 'No internet service']

🧩 DeviceProtection unique values:
['No' 'Yes' 'No internet service']

🧩 TechSupport unique values:
['No' 'Yes' 'No internet service']

🧩 StreamingTV unique values:
['No' 'Yes' 'No internet service']

🧩 StreamingMovies unique values:
['No' 'Yes' 'No internet service']

🧩 Contract unique values:
['Month-to-month' 'One year' 'Two year']

🧩 PaymentMethod unique values:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [30]:
service_cols = [
    "MultipleLines", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies"
]

for ser in service_cols:
    df_clean[ser]= df_clean[ser].replace({"No internet service":"No","No phone service":"No"},)

In [31]:
for i in service_cols:
    print(f"\n🧩 {i} unique values:")
    print(df_clean[i].unique())

🧩 MultipleLines unique values:
['No' 'Yes']

🧩 OnlineBackup unique values:
['Yes' 'No']

🧩 DeviceProtection unique values:
['No' 'Yes']

🧩 TechSupport unique values:
['No' 'Yes']

🧩 StreamingTV unique values:
['No' 'Yes']

🧩 StreamingMovies unique values:
['No' 'Yes']

In [32]:
for i in obj_cols:
    print(f"\n {i} unique value:")
    print(df_clean[i].unique())

 MultipleLines unique value:
['No' 'Yes']

 InternetService unique value:
['DSL' 'Fiber optic' 'No']

 OnlineBackup unique value:
['Yes' 'No']

 DeviceProtection unique value:
['No' 'Yes']

 TechSupport unique value:
['No' 'Yes']

 StreamingTV unique value:
['No' 'Yes']

 StreamingMovies unique value:
['No' 'Yes']

 Contract unique value:
['Month-to-month' 'One year' 'Two year']

 PaymentMethod unique value:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [33]:
order = {"Yes":1,"No":0}
for i in service_cols:
    df_clean[i]=df_clean[i].map(order)

In [34]:
for i in obj_cols:
    print(f"\n{i}uniques")
    print(df_clean[i].value_counts())

MultipleLinesuniques
MultipleLines
0    4072
1    2971
Name: count, dtype: int64

InternetServiceuniques
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

OnlineBackupuniques
OnlineBackup
0    4614
1    2429
Name: count, dtype: int64

DeviceProtectionuniques
DeviceProtection
0    4621
1    2422
Name: count, dtype: int64

TechSupportuniques
TechSupport
0    4999
1    2044
Name: count, dtype: int64

StreamingTVuniques
StreamingTV
0    4336
1    2707
Name: count, dtype: int64

StreamingMoviesuniques
StreamingMovies
0    4311
1    2732
Name: count, dtype: int64

Contractuniques
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

PaymentMethoduniques
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [35]:
last_encode = ["Contract","PaymentMethod","InternetService"]

In [36]:
df_clean= pd.get_dummies(df_clean,columns=["InternetService"],drop_first=True)

In [37]:
df_clean = pd.get_dummies(df_clean , columns=["Contract"],drop_first=True)

In [38]:
df_clean = pd.get_dummies(
    df_clean,
    columns=["PaymentMethod"],
    drop_first=True
)

In [39]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   Partner                                7043 non-null   int64
 2   Dependents                             7043 non-null   int64
 3   tenure                                 7043 non-null   int64
 4   PhoneService                           7043 non-null   int64
 5   MultipleLines                          7043 non-null   int64
 6   OnlineSecurity                         7043 non-null   int64
 7   OnlineBackup                           7043 non-null   int64
 8   DeviceProtection                       7043 non-null   int64
 9   TechSupport                            7043 non-null   int64
 10  StreamingTV                            7043 non-null   int64
 11  StreamingMovies                        7043 non-null   int64
 12  PaperlessBilling                       7043 non-null   int64
 13  MonthlyCharges                         7043 non-null   float64
 14  TotalCharges                           7032 non-null   float64
 15  Churn                                  7043 non-null   int64
 16  gender_Male                            7043 non-null   int64
 17  InternetService_Fiber optic            7043 non-null   bool
 18  InternetService_No                     7043 non-null   bool
 19  Contract_One year                      7043 non-null   bool
 20  Contract_Two year                      7043 non-null   bool
 21  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 22  PaymentMethod_Electronic check         7043 non-null   bool
 23  PaymentMethod_Mailed check             7043 non-null   bool
dtypes: bool(7), float64(2), int64(15)
memory usage: 983.7 KB

In [40]:
for i in df_clean.columns:
    print(f"\n{i} uniques:")
    print(df_clean[i].value_counts())

SeniorCitizen uniques:
SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

Partner uniques:
Partner
0    3641
1    3402
Name: count, dtype: int64

Dependents uniques:
Dependents
0    4933
1    2110
Name: count, dtype: int64

tenure uniques:
tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

PhoneService uniques:
PhoneService
1    6361
0     682
Name: count, dtype: int64

MultipleLines uniques:
MultipleLines
0    4072
1    2971
Name: count, dtype: int64

OnlineSecurity uniques:
OnlineSecurity
0    5024
1    2019
Name: count, dtype: int64

OnlineBackup uniques:
OnlineBackup
0    4614
1    2429
Name: count, dtype: int64

DeviceProtection uniques:
DeviceProtection
0    4621
1    2422
Name: count, dtype: int64

TechSupport uniques:
TechSupport
0    4999
1    2044
Name: count, dtype: int64

StreamingTV uniques:
StreamingTV
0    4336
1    2707
Name: count, dtype: int64

StreamingMovies uniques:
StreamingMovies
0    4311
1    2732
Name: count, dtype: int64

PaperlessBilling uniques:
PaperlessBilling
1    4171
0    2872
Name: count, dtype: int64

MonthlyCharges uniques:
MonthlyCharges
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: count, Length: 1585, dtype: int64

TotalCharges uniques:
TotalCharges
20.20      11
19.75       9
20.05       8
19.90       8
19.65       8
           ..
6849.40     1
692.35      1
130.15      1
3211.90     1
6844.50     1
Name: count, Length: 6530, dtype: int64

Churn uniques:
Churn
0    5174
1    1869
Name: count, dtype: int64

gender_Male uniques:
gender_Male
1    3555
0    3488
Name: count, dtype: int64

InternetService_Fiber optic uniques:
InternetService_Fiber optic
False    3947
True     3096
Name: count, dtype: int64

InternetService_No uniques:
InternetService_No
False    5517
True     1526
Name: count, dtype: int64

Contract_One year uniques:
Contract_One year
False    5570
True     1473
Name: count, dtype: int64

Contract_Two year uniques:
Contract_Two year
False    5348
True     1695
Name: count, dtype: int64

PaymentMethod_Credit card (automatic) uniques:
PaymentMethod_Credit card (automatic)
False    5521
True     1522
Name: count, dtype: int64

PaymentMethod_Electronic check uniques:
PaymentMethod_Electronic check
False    4678
True     2365
Name: count, dtype: int64

PaymentMethod_Mailed check uniques:
PaymentMethod_Mailed check
False    5431
True     1612
Name: count, dtype: int64

In [41]:
y= df_clean["Churn"]
X= df_clean.drop("Churn",axis=1)

In [42]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_Scaled = scaler.fit_transform(X)

In [43]:
type(X_Scaled)
X_Scaled

array([[-0.43991649,  1.03453023, -0.65401193, ..., -0.52504733,
         1.40641839, -0.54480692],
       [-0.43991649, -0.96662231, -0.65401193, ..., -0.52504733,
        -0.71102597,  1.83551265],
       [-0.43991649, -0.96662231, -0.65401193, ..., -0.52504733,
        -0.71102597,  1.83551265],
       ...,
       [-0.43991649,  1.03453023,  1.5290241 , ..., -0.52504733,
         1.40641839, -0.54480692],
       [ 2.27315869,  1.03453023, -0.65401193, ..., -0.52504733,
        -0.71102597,  1.83551265],
       [-0.43991649, -0.96662231, -0.65401193, ..., -0.52504733,
        -0.71102597, -0.54480692]], shape=(7043, 23))

In [44]:
from sklearn.model_selection import train_test_split

X_train ,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42,stratify=y)

## !!!!!! Straify =  y çok ÖNEMLİ DATA İMBALANCED OLDUĞU İÇİN BUNU KORUMALIYIZ

In [45]:
from sklearn.linear_model import LogisticRegression


model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train,y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
X.isnull().sum().sort_values(ascending=False)

In [51]:
X["TotalCharges"] = X["TotalCharges"].fillna(
    X["TotalCharges"].median()
)

In [52]:
X.isnull().sum().sort_values(ascending=False)

SeniorCitizen                            0
PaperlessBilling                         0
PaymentMethod_Electronic check           0
PaymentMethod_Credit card (automatic)    0
Contract_Two year                        0
Contract_One year                        0
InternetService_No                       0
InternetService_Fiber optic              0
gender_Male                              0
TotalCharges                             0
MonthlyCharges                           0
StreamingMovies                          0
Partner                                  0
StreamingTV                              0
TechSupport                              0
DeviceProtection                         0
OnlineBackup                             0
OnlineSecurity                           0
MultipleLines                            0
PhoneService                             0
tenure                                   0
Dependents                               0
PaymentMethod_Mailed check               0
dtype: int64

##  ÖNCEKİ X DE NAN ÇIKYTIĞI İÇİN TEKRAR SCALER TRAİN TEST YAPICAZ

# ÖNCE TRAİN/TEST SONRA SCALER AW DATA LEAKAGE

In [55]:
from sklearn.model_selection import  train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
    
)

In [56]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [57]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [58]:
X.isnull().sum().sort_values(ascending=False)

SeniorCitizen                            0
PaperlessBilling                         0
PaymentMethod_Electronic check           0
PaymentMethod_Credit card (automatic)    0
Contract_Two year                        0
Contract_One year                        0
InternetService_No                       0
InternetService_Fiber optic              0
gender_Male                              0
TotalCharges                             0
MonthlyCharges                           0
StreamingMovies                          0
Partner                                  0
StreamingTV                              0
TechSupport                              0
DeviceProtection                         0
OnlineBackup                             0
OnlineSecurity                           0
MultipleLines                            0
PhoneService                             0
tenure                                   0
Dependents                               0
PaymentMethod_Mailed check               0
dtype: int64

In [59]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred= model.predict(X_test_scaled)

print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

[[749 286]
 [ 80 294]]

In [61]:
coef_df = pd.Series(
    model.coef_[0],
    index=X.columns
).sort_values()

In [62]:
print(coef_df)

tenure                                  -1.153424
MonthlyCharges                          -0.937607
InternetService_No                      -0.657975
Contract_Two year                       -0.620038
Contract_One year                       -0.297112
OnlineSecurity                          -0.122110
Dependents                              -0.104808
TechSupport                             -0.091712
OnlineBackup                            -0.003978
PaymentMethod_Credit card (automatic)   -0.001001
Partner                                  0.008620
gender_Male                              0.016131
PaymentMethod_Mailed check               0.020995
PhoneService                             0.029124
DeviceProtection                         0.050462
SeniorCitizen                            0.056490
PaperlessBilling                         0.164820
PaymentMethod_Electronic check           0.188311
MultipleLines                            0.192850
StreamingTV                              0.256759
StreamingMovies                          0.270008
TotalCharges                             0.488735
InternetService_Fiber optic              0.767833
dtype: float64

In [63]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

In [64]:
param_grid = [
    {
        "model__penalty": ["l1"],
        "model__C": [0.01, 0.1, 1, 10],
        "model__solver": ["liblinear"],
        "model__class_weight": [None, "balanced"]
    },
    {
        "model__penalty": ["l2"],
        "model__C": [0.01, 0.1, 1, 10],
        "model__solver": ["liblinear", "lbfgs"],
        "model__class_weight": [None, "balanced"]
    }
]

In [65]:
from sklearn.model_selection import GridSearchCV

grid_recall = GridSearchCV(
    pipeline,
    param_grid,
    scoring="recall",
    cv=5,
    n_jobs=-1
)

grid_recall.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid=[{'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l1'],
                          'model__solver': ['liblinear']},
                         {'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l2'],
                          'model__solver': ['liblinear', 'lbfgs']}],
             scoring='recall')

In [67]:
grid_precision = GridSearchCV(
    pipeline,
    param_grid,
    scoring="precision",
    cv=5,
    n_jobs=-1
)

grid_precision.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid=[{'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l1'],
                          'model__solver': ['liblinear']},
                         {'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l2'],
                          'model__solver': ['liblinear', 'lbfgs']}],
             scoring='precision')

In [68]:
grid_f1 = GridSearchCV(
    pipeline,
    param_grid,
    scoring="f1",
    cv=5,
    n_jobs=-1
)

grid_f1.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid=[{'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l1'],
                          'model__solver': ['liblinear']},
                         {'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l2'],
                          'model__solver': ['liblinear', 'lbfgs']}],
             scoring='f1')

In [71]:
grid_auc = GridSearchCV(
    pipeline,
    param_grid,
    scoring="roc_auc",
    cv=5,
    n_jobs=-1
)

grid_auc.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid=[{'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l1'],
                          'model__solver': ['liblinear']},
                         {'model__C': [0.01, 0.1, 1, 10],
                          'model__class_weight': [None, 'balanced'],
                          'model__penalty': ['l2'],
                          'model__solver': ['liblinear', 'lbfgs']}],
             scoring='roc_auc')

In [72]:
from sklearn.metrics import (
    precision_score, recall_score, f1_score, roc_auc_score
)

def evaluate(model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]
    
    return {
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_prob)
    }

In [73]:
results = {
    "Recall Optimized": evaluate(grid_recall.best_estimator_, X_test, y_test),
    "Precision Optimized": evaluate(grid_precision.best_estimator_, X_test, y_test),
    "F1 Optimized": evaluate(grid_f1.best_estimator_, X_test, y_test),
    "ROC-AUC Optimized": evaluate(grid_auc.best_estimator_, X_test, y_test),
}

import pandas as pd
pd.DataFrame(results).T

                     precision    recall        f1   roc_auc
Recall Optimized      0.486312  0.807487  0.607035  0.836781
Precision Optimized   0.654930  0.497326  0.565350  0.835830
F1 Optimized          0.504303  0.783422  0.613613  0.841422
ROC-AUC Optimized     0.654088  0.556150  0.601156  0.841001

# 📊 Telco Customer Churn – End-to-End Logistic Regression Case Study

In this project, we analyzed the customer churn problem of a telecom company using machine learning. Our goal was to predict customers who are likely to leave and develop business strategies to retain them.

---

## 1️⃣ Exploratory Data Analysis (EDA)
First, we checked the distribution of the target variable ("Churn").
* **No Churn (0):** ~74%
* **Churn (1):** ~26%

➡️ **Insight:** The dataset is **imbalanced**. We must choose our model parameters and evaluation metrics accordingly.

---

## 2️⃣ Data Cleaning
The `TotalCharges` column was an "object" type and contained empty strings. We converted it to numeric format and handled missing values.

```python
# Converting to numeric and filling NaN values
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"].str.strip(), errors="coerce")
df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

# Simplifying service columns
service_cols = ["OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"]
for col in service_cols:
    df[col] = df[col].replace({"No internet service": "No"})

# Binary Encoding (Yes/No to 1/0)
binary_cols = ["Partner", "Dependents", "PhoneService", "PaperlessBilling", "MultipleLines"] + service_cols
for col in binary_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

# One-Hot Encoding for multi-category variables
df = pd.get_dummies(df, columns=["InternetService", "Contract", "PaymentMethod", "gender"], drop_first=True)

To prevent data leakage, we split the data into training (80%) and testing (20%) sets. We used stratify=y to maintain the class balance in both sets.

In [ ]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])
pipeline.fit(X_train, y_train)

7️⃣ Coefficient Analysis (Business Insights)
Analyzing the model coefficients helped us understand why customers leave:

Tenure ↑: Longer loyalty reduces churn risk.

Two-year Contract ↑: Strongly prevents churn.

Fiber Optic ↑: Increases churn risk (possible service quality issues).

Tech Support ↑: Reduces churn.