In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Original_data_with_more_rows.csv")

In [3]:
df.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    30641 non-null  int64
 1   Gender        30641 non-null  object
 2   EthnicGroup   30641 non-null  object
 3   ParentEduc    30641 non-null  object
 4   LunchType     30641 non-null  object
 5   TestPrep      30641 non-null  object
 6   MathScore     30641 non-null  int64
 7   ReadingScore  30641 non-null  int64
 8   WritingScore  30641 non-null  int64
dtypes: int64(4), object(5)
memory usage: 2.1+ MB

In [7]:
drop_columns = ["Unnamed: 0","EthnicGroup","LunchType"]

In [ ]:
#2 tpys of drop data 
#df_clean= df.drop(columns=drop_columns)
#or 
#df.drop(columns=drop_columns,inplace=True)

In [8]:
df.drop(columns=drop_columns,inplace=True)

In [9]:
df.head(1)

   Gender         ParentEduc TestPrep  MathScore  ReadingScore  WritingScore
0  female  bachelor's degree     none         72            72            74

## DATA RENAME

In [11]:
df.rename(columns={"ParentEduc":"Parent_Education","TestPrep":"Test_Preparatıon"})

,Gender,Parent_Education,Test_Preparatıon,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30636,male,some high school,none,56,47,51
30637,male,associate's degree,none,74,75,72
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66

In [15]:
df.duplicated().value_counts()
#True      1356 there is 1356 row

False    29285
True      1356
Name: count, dtype: int64

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
30635    False
30636    False
30638    False
30639    False
30640    False
Length: 29285, dtype: bool

In [19]:
#Length: 29285 but df show us 30640 row its definetly false we need to fix it
df.reset_index(inplace=True)

In [20]:
df

,index,Gender,ParentEduc,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,bachelor's degree,none,72,72,74
1,1,female,some college,completed,69,90,88
2,2,female,master's degree,none,90,95,93
3,3,male,associate's degree,none,47,57,44
4,4,male,some college,none,76,78,75
...,...,...,...,...,...,...,...
29280,30635,male,some high school,completed,64,59,64
29281,30636,male,some high school,none,56,47,51
29282,30638,male,some college,none,36,29,27
29283,30639,male,some high school,completed,43,34,39
29284,30640,female,associate's degree,none,52,68,66

In [21]:
## İs there any Nan values in our data

In [23]:
df.isna().sum()

index           0
Gender          0
ParentEduc      0
TestPrep        0
MathScore       0
ReadingScore    0
WritingScore    0
dtype: int64

In [ ]:
df["Gender"].replace("male",value="M",inplace=True)
df["Gender"].replace("female",value="F",inplace=True)
                        #or
      #df["Gender"] = df["Gender"].replace({"male": "M", "female": "F"})

                         #or
     #s = df["Gender"].astype("string").str.strip().str.lower()
    
     #df["Gender"] = s.map({"male": "M", "female": "F"})